### ISSUE TITLE
Research and setup CI/CD pipeline

### ISSUE THREAD

**Issue by brianliu1412** [cse110-spr23-group18/cse110-sp23-group18#10]
- [x] Setup code linting
- [x] Code style enforcement (might not be able to be automated?)
- [x] Code quality tool (i.e. Codeclimate, Codacy)
- [x] #29

**Comment by CatFish47** [comment]
CodeQL and ESLint github actions workflows have been setup

**Comment by CatFish47** [comment]
Was messing around with the checkboxes: unit testing / testing not finished yet, currently an issue on #28

**Comment by CatFish47** [comment]
Code styling guidelines can generally be found in either the `admin/guidelines` directory, such as naming conventions, and the more lintable conventions can be found [here](https://github.com/airbnb/javascript), as we are using AirBnb JS guidelines due to its general practicality and in general we agree with the guidelines as a good coding standard.

**Comment by CatFish47** [comment]
Moved to issue #54 and #55
